[package]
name = "shim"
version = "0.1.0"
edition = "2024"

[dependencies]
shim-macros = { path = "../shim-macros" }

[dependencies.winapi]
version = "0.3.9"
features = ["sysinfoapi", "libloaderapi"]
