[package]
name = "version"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
cdylib-shim = { path = "../../crates/cdylib-shim" }

[dependencies.winapi]
version = "0.3.9"
