[package]
name = "cdylib-shim-macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
convert_case = "0.8.0"
itertools = "0.14.0"
object = "0.36.7"
proc-macro2 = "1.0.94"
quote = "1.0.40"

[dependencies.syn]
version = "2.0.100"
features = ["full"]
