[package]
name = "shim"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.18.0"
shim-codegen = { path = "../shim-codegen" }
shim-core = { path = "../shim-core" }
widestring = "0.5.1"
winapi = { version = "0.3.9", features = ["sysinfoapi", "libloaderapi"] }
