[package]
name = "cdylib-shim"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
cdylib-shim-macros = { path = "../cdylib-shim-macros" }

[dependencies.winapi]
version = "0.3.9"
features = ["sysinfoapi", "libloaderapi"]
